### ISSUE TITLE
Better knitr integration

### ISSUE THREAD

**Issue by wch** [wch/webshot#1]
It would be useful to be able to put calls to `webshot` in a knitr document. Also, perhaps have an option so that if the image already exists, don't try to re-capture it.

**Comment by smbache** [comment]
+1

**Comment by yihui** [comment]
I started working on it this week. Any plan for a CRAN release?

**Comment by wch** [comment]
Sorry, no plans for a CRAN release because webshot requires PhantomJS. Are you looking to make some changes to webshot?

**Comment by yihui** [comment]
No, I'm making changes in knitr (basically calling webshot when the output object is an HTML widget or shiny app).

I think this is fine for CRAN as long as 1) you state PhantomJS in SystemRequirements in DESCRIPTION, and 2) you do not put examples in the help docs (so that R CMD check won't complain); you could have examples in vignettes, e.g. you can call `knitr::knit_ext()` if PhantomJS is not found so that R CMD check won't fail on CRAN.
